# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapboxChallenge' do
 platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



 # React Native
 pod 'React', path: '../node_modules/react-native', subspecs: [
   # Comment out any unneeded subspecs to reduce bundle size.
   'Core',
   'DevSupport',
   'RCTActionSheet',
   'RCTAnimation',
   'RCTBlob',
   'RCTCameraRoll',
   'RCTGeolocation',
   'RCTImage',
   'RCTNetwork',
   'RCTPushNotification',
   'RCTSettings',
   'RCTTest',
   'RCTText',
   'RCTVibration',
   'RCTWebSocket',
   'RCTLinkingIOS'
 ]

 # Flexbox Layout Manager Used By React Native
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
 
 # Mapbox
 pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  # Pods for MapboxChallenge

end
